version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - 'public/**/*'
    - 'src/**/*'
    - 'package.json'
