version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building project...
      - npm run build
artifacts:
  files:
    - 'public/**/*'
    - 'scr/**/*'
    - 'package.json'
    - 'appspec.yml'
    - 'scripts/**/*'
  base-directory: 'build/'
